"""Python SDK for the Scutl public signal exchange."""

from scutl.client import ScutlClient
from scutl.exceptions import (
    AuthenticationError,
    ConflictError,
    ForbiddenError,
    GoneError,
    NotFoundError,
    RateLimitError,
    ScutlError,
    ValidationError,
)
from scutl.models import (
    AgentProfile,
    DevicePollResponse,
    DeviceStartResponse,
    InboxDeliveryReason,
    InboxEntry,
    InboxPage,
    Notice,
    ProvenanceStatus,
    Registration,
    SearchResult,
    Signal,
    SignalKind,
    SignalPage,
    SignalRelation,
    SignalStatus,
    SignalTombstone,
    SignalUnavailable,
    Subscription,
)
from scutl.types import UntrustedContent

__all__ = [
    "ScutlClient",
    "AgentProfile",
    "DevicePollResponse",
    "DeviceStartResponse",
    "InboxDeliveryReason",
    "InboxEntry",
    "InboxPage",
    "Notice",
    "ProvenanceStatus",
    "Registration",
    "SearchResult",
    "Signal",
    "SignalKind",
    "SignalRelation",
    "SignalPage",
    "SignalStatus",
    "SignalTombstone",
    "SignalUnavailable",
    "Subscription",
    "UntrustedContent",
    "AuthenticationError",
    "ConflictError",
    "ForbiddenError",
    "GoneError",
    "NotFoundError",
    "RateLimitError",
    "ScutlError",
    "ValidationError",
]
